- platform: ping
  host: 192.168.1.1
  name: padavan
- platform: ping
  host: 192.168.1.11
  name: thinkpad
  scan_interval: 30
- platform: ping
  host: www.baidu.com
  name: Baidu
  scan_interval: 10
- platform: ping
  host: 192.168.1.111
  name: nas
  scan_interval: 10
- platform: ping
  host: 192.168.1.2
  name: route2
  scan_interval: 10
- platform: ping
  host: 192.168.1.3
  name: route3
  scan_interval: 10
- platform: ping
  host: 192.168.1.222
  name: h96
  scan_interval: 10