# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
homekit:
  - filter:
      include_domains:
        - switch
        - light
        - media_player
        - sensor
        - binary_sensor
mobile_app:
#discovery:
wake_on_lan:
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
binary_sensor:
  - platform: ping
    host: 192.168.1.8
    name: NAS
  - platform: ping
    host: 192.168.1.3
    name: D191G
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: 9A62A0F6915A483C

# molobot:
  # phone: 15513084760  # 天猫精灵绑定的手机号
  # password: 19890612
#recorder:
 # purge_interval: 7
  #purge_keep_days: 7
  #db_url: mysql://hass:159753000@127.0.0.1/hassdatabase?charset=utf8

  
