# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
mobile_app:
wake_on_lan:
homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    switch.1f_woshi:
      icon: mdi:ceiling-light-outline
      friendly_name: 一楼卧室灯
    switch.woshi_light:
      friendly_name: 二楼卧室灯
      icon: mdi:outdoor-lamp
    switch.ciwo_light:
      friendly_name: 一楼次卧灯
      icon: mdi:lightbulb-variant-outline
    climate.haier: 
      friendly_name: 客厅空调
      icon: mdi:air-conditioner
    media_player.my_media_player:
      source_list:
        - Channel/input from my available sources
mqtt:
  switch:
    - unique_id: mqtt_sonoff
      name: "sonoff1"
      state_topic: "stat/sonoff/POWER"
      command_topic: "cmnd/sonoff/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: true

# http:
  # server_port: 8123  #可以不要
  # # base_url: https://home.miaoyang.info  # 你的阿里云域名
  # ssl_certificate: /config/ssl_keys/home.miaoyang.info_bundle.pem   #公钥文件地址，注意放在有读取权限的文件夹
  # ssl_key: /config/ssl_keys/home.miaoyang.info.key 
  # trusted_proxies:
    # - 10.0.0.200
    # - 192.168.1.0/24
  # use_x_forwarded_for: true
  # ip_ban_enabled: true
  # login_attempts_threshold: 5
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech

input_text: 
  text1:
    name: 发送通知文本
  text2:
    name: 发给小爱同学
input_button:
  message:
    name: 点击发送
    icon: mdi:cellphone-message
  xiaoai:
    name: 小爱说话
    icon: mdi:speaker
frontend: 
  themes: !include_dir_merge_named themes
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://miaoyang.iok.la:1880/'
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: "1234"
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

tts:
  - platform: edge_tts
    service_name: edge_tts_say # service: tts.xiaomo_say
    language: zh-CN-XiaoxiaoNeural
    volume: +10%
weather:
  - platform: heweather
    location: 101100106    # 填写你所在区域代码Location_ID,https://github.com/qwd/LocationList/blob/master/China-City-List-latest.csv
    key: a4de9580a88d4411bef9344b37273e2a             # api平台申请的key
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: 1510C516FBD4464F
    - key: qewnth1ff3byk4rf
logger:
  default: warn
  logs:
    custom_components.haier: debug