####一楼卧室按钮自动化####

- alias: 1f woshi switch on long press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001839247
      click_type: long_click_press
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.yi_lou_wo_shi_deng
      - light.gateway_light_286c07f0c4e5
- alias: 1f woshi switch on double press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001839247
      click_type: double
  # condition:
    # condition: sun
    # after: sunset
  action:
    service: light.toggle
    data:
      brightness: 80
      rgb_color: [15, 30, 60]
    entity_id:
      - light.gateway_light_286c07f0c4e5
- alias: 1f woshi switch on single press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001839247
      click_type: single
  condition:
    condition: sun
    after: sunset
  action:
    service: switch.toggle
    entity_id:
      - switch.yi_lou_wo_shi_deng
####二楼客厅按钮自动化####
- alias: 2f keting switch on single press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21774
      click_type: single
  condition:
    condition: sun
    after: sunset
  action:
    service: switch.toggle
    entity_id:
      - switch.er_lou_ke_ting_deng
- alias: 2f keting switch on long press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21774
      click_type: long_click_press
  action:
    service: switch.turn_off
    entity_id:
      - switch.slot2_s1
      - switch.slot2_s2
- alias: 2f keting switch on double press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001a21774
      click_type: double
  action:
    - service: switch.turn_on
      entity_id: switch.slot2_s1
    - delay:
       seconds: 5
    - service: switch.turn_on
      entity_id: switch.slot2_s2
####二楼客厅人体感应自动化####
- alias: 2f keting motion on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d5c57
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    service: switch.turn_on
    entity_id: switch.keting_light
- alias: 2f keting motion off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d5c57
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 30
  # condition:
    # condition: sun
    # after: sunset
  action:
    service: switch.turn_off
    entity_id: switch.keting_light
####二楼卧室人体感应自动化####
- alias: 2f woshi motion on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015dbaec
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    service: switch.turn_on
    entity_id: switch.er_lou_wo_shi_deng
- alias: 2f woshi motion off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015dbaec
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 30
  # condition:
    # condition: sun
    # after: sunset
  action:
    service: switch.turn_off
    entity_id: switch.er_lou_wo_shi_deng
####一楼卧室人体感应自动化####
- alias: 1f woshi motion on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d2507
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    service: light.turn_on
    data:
      brightness: 80
      rgb_color: [55, 200, 30]
    entity_id: light.gateway_light_286c07f0c4e5
- alias: 1f woshi motion off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d2507
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 30
  # condition:
    # condition: sun
    # after: sunset
  action:
    service: light.turn_off
    entity_id: light.gateway_light_286c07f0c4e5
####晚上一楼关主灯开夜灯####
- alias: IF TURN OFF 1F WOSHI LIGHT THAN TURN ON MI LIGHT
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.yi_lou_wo_shi_deng
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '19:00:00'
        before: '07:00:00'
  action:
  - service: light.turn_on
    data:
      brightness: 100
      rgb_color: [253,56, 68]
    entity_id: light.gateway_light_286c07f0c4e5


###早上9点把所有的灯关一遍###
- alias: turn off all light
  initial_state: 'on'
  trigger:
      platform: time
      at: '9:00:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.yi_lou_wo_shi_deng
      - switch.er_lou_wo_shi_deng
      - switch.keting_light
      - light.gateway_light_286c07f0c4e5
####网关整点报时###
- alias: Hourly Chime
  initial_state: 'on'
  trigger:
      platform: time_pattern
      minutes: 00
      seconds: 01
  condition:
      condition: time
      after: '06:00:00'
      before: '23:00:00'
    # - condition: state
      # entity_id: device_tracker.phone_me
      # state: 'home'
  action:
      service: xiaomi_aqara.play_ringtone
      data_template:
        gw_mac: 28:6C:07:F0:C4:E5
        ringtone_id: 10001
        ringtone_vol: 10
####小米开关插座半小时开关一次####
- alias: spmini2 switch control
  initial_state: 'on'
  trigger:
      platform: time_pattern
      minutes: "/30"
  action:
      service: switch.toggle
      entity_id:
        - switch.sap_mini2_switch