# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
####博联RM####
- platform: broadlink
  mac: '34:ea:34:e9:ba:18'
  switches:
    woshi_light:
      command_on: 'sg40AAocHQkKHB0JChwdCgocHQkKHAobChwKHAobChsdCR0JCgABGwocHQkKHBwKChwdCQocHAkAAAAA'
      command_off: 'shQ0ABwKChscCQobHAoKGxwJChscCgocHAkKGxwJChsKHBwJHAoKGwocChsKGwoAARgKHBwKChsAAAAA'    
      friendly_name: "二楼卧室灯"
    keting_light:
      command_on: 'shA0AAocHAkKHBwJChwcCQocHAkKHBwKChscCQocHAkKHAocChwKGxwJHAkKHAobCgABGQobHAoAAAAA'
      command_off: 'sgs0AAobHAkKGxwJChscCRwJHAkKGwobChwKGwobChsKAAEVChscCQobHAkKHBwJChscCQobHAkAAAAA'
      friendly_name: "二楼客厅灯"
    1f_woshi:
      command_on: 'shI0AAobHAoKHBwJChscCQobHAkKGx0JChwcCQocHAoKHAocChwKGxwJHAkKHAocCgABGRwKHAkAAAAA'
      command_off: 'sgs0AAoAARUcCRwJChscCQobHAkKGxwJChscCQobHAkKGxwJChscCRwJHAkKGwobChsKGwobChsAAAAA'
      friendly_name: "一楼卧室灯"
####博联SPMINI####

####SONOFF-BASIC####
# - platform: mqtt
  # name: "SONOFF01"
  # state_topic: "stat/sonoff01/POWER"
  # command_topic: "cmnd/sonoff01/POWER"
  # qos: 1
  # payload_on: "ON"
  # payload_off: "OFF"
  # retain: true
# - platform: mqtt
  # name: "SONOFF02"
  # state_topic: "stat/sonoff02/POWER"
  # command_topic: "cmnd/sonoff02/POWER"
  # qos: 1
  # payload_on: "ON"
  # payload_off: "OFF"
  # retain: true
###鸿雁插排####
####WOL-NAS####
- platform: wake_on_lan
  mac: 00:E0:70:86:C7:BA
  host: 192.168.1.200
  name: MY-NAS
  turn_off:
    service: shell_command.nasoff
