#####打开KODI时打开NAS#####
- alias: kodinas
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'off'
    to: 'idle'
  action:
    service: switch.turn_on
    entity_id: 
      - switch.mynas
####家里没人时执行的操作####
- alias: 'Away Mode'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
  action:
    service: light.turn_on
    entity_id: 
      - light.gateway_light_286c07f0c4e5
- alias: 'Home Mode'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  action:
    service: light.turn_off
    entity_id: 
      - light.gateway_light_286c07f0c4e5
###早上9点把所有的灯关一次###
- alias: turn off all light
  initial_state: 'on'
  trigger:
    - platform: time
      at: '8:00:00'
  action:
  - service: switch.turn_off
    entity_id: 
      - switch.1f_woshi
      - switch.woshi_light
      - switch.keting_light
####网关整点报时###

- alias: Hourly Chime
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: 00
      seconds: 01
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:00:00'
    # - condition: state
      # entity_id: device_tracker.phone_me
      # state: 'home'
  action:
    - service: xiaomi_aqara.play_ringtone
      data_template:
        gw_mac: 28:6C:07:F0:C4:E5
        ringtone_id: 10001
        ringtone_vol: 10
####晚上一楼关主灯开夜灯####
- alias: IF TURN OFF 1F WOSHI LIGHT THAN TURN ON MI LIGHT
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.1f_woshi
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '19:00:00'
        before: '07:00:00'
  action:
  - service: homeassistant.turn_on
    entity_id: light.gateway_light_286c07f0c4e5