####二楼卧室有活动开主灯，没活动关主灯###
- alias: 2FWOSHIDENGKAI
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d5c57
    from: 'off'
    to: 'on'
  condition:
    condition: sun  
    after: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.woshi_light
- alias: 2FWOSHIDENGGUAN
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d5c57
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 3
      seconds: 30
  condition:
    condition: time
    after: '19:00:00'
    before: '08:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.woshi_light
####晚上一楼有活动开夜灯，没活动关夜灯###
- alias: 1FWOSHIDENGKAI
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d2507
    from: 'off'
    to: 'on'   
  condition:
    condition: time
    after: '21:00:00'
    before: '08:00:00'
  action:
  - service: homeassistant.turn_on
    entity_id: light.gateway_light_286c07f0c4e5
- alias: 1FWOSHIDENGGUAN
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015d2507
    from: 'on'
    to: 'off' 
    for:
      hours: 0
      minutes: 3
      seconds: 30    
  condition:
    condition: time
    after: '21:00:00'
    before: '08:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: light.gateway_light_286c07f0c4e5

####二楼客厅有活动开主灯，没活动关主灯###
- alias: 2FKETINGDENGKAI
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015dbaec
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun  
        after: sunset
      - condition: state
        entity_id: switch.woshi2
        state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.keting_light
- alias: 2FKETINGDENGGUAN
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d00015dbaec
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 3
      seconds: 30
  condition:
    condition: and
    conditions:
      - condition: sun  
        after: sunset
      - condition: state
        entity_id: switch.keting_light
        state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.keting_light