####小米插座###

- alias: XIAOMI_SWITCH_CTL_ON
  trigger: 
  - platform: time
    at: '20:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.plug_158d00015d1bf5
- alias: XIAOMI_SWITCH_CTL_OFF
  trigger: 
  - platform: time
    at: '6:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.plug_158d00015d1bf5
####SP-MIMI鱼店橱窗灯太阳落山后20分钟开灯19点00关灯####
- alias: spmini_SWITCH_CTL_ON
  trigger: 
  - platform: time
    at: '19:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.spmini
- alias: spmini_SWITCH_CTL_OFF
  trigger: 
  - platform: time
    at: '20:30:00'
  action:
  - service: switch.turn_off
    entity_id: switch.spmini   
 ####鱼店鱼缸灯每天9点30开灯19点00分关灯###
- alias: dakaiyugangdeng
  trigger: 
  - platform: time
    at: '9:00:00'
  action:
  - service: switch.turn_on
    entity_id: 
      - switch.device1 
      - switch.fish1
- alias: guanbiyugangdeng
  trigger: 
  - platform: time
    at: '20:00:00'
  action:
  - service: switch.turn_off
    entity_id: 
      - switch.device1  
      - switch.fish1   
      - switch.device4
###鱼店氧气泵每隔10分钟开关一次####      
- alias: dakaiyangqibeng
  trigger: 
  - platform: time
    minutes: '/10'
    seconds: 00
  action:
  - service: switch.toggle
    entity_id: 
      - switch.device2
###鱼缸过滤泵每15分钟开关一次####
- alias: guanbiguolvbeng
  trigger: 
  - platform: time
    minutes: '/15'
    seconds: 00
  action:
  - service: switch.toggle
    entity_id: 
      - switch.fish3
      - switch.device3
      - switch.fish2